### ISSUE TITLE
Multiple recaptcha breaks form on FF

### ISSUE THREAD

**Issue by Stiofan** [UsersWP/uwp_recaptcha#15]
if multiple forms on page it loads the api twice instead of loading a callback to laod both forms.
Also please add an option to add  recaptcha to standard WP registration form.

**Comment by kprajapatii** [comment]
Fixed: if multiple forms on page it loads the api twice instead of loading a callback to load both forms.

**Comment by wpdev10** [comment]
Merged: https://github.com/UsersWP/uwp_recaptcha/pull/16
